# Default values for postgrest.
replicaCount: 1

image:
  repository: postgrest/postgrest
  pullPolicy: IfNotPresent
  tag: "v10.0.0"

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: postgrest.local
      paths:
        - path: /
          pathType: ImplementationSpecific

db:
  uri: ""
