apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgrest
  labels:
    app: postgrest
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      # securityContext:
      #   runAsUser: 1001
      #   runAsGroup: 1001
      #   fsGroup: 1001
      containers:
        - name: postgrest
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PGRST_DB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-credentials
                  key: uri
            - name: PGRST_DB_ANON_ROLE
              value: {{ .Values.db.anon_role | quote }}
            - name: PGRST_DB_SCHEMA
              value: {{ .Values.db.schema | quote }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
