apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgrest
  labels:
    app: postgrest
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      containers:
        - name: postgrest
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PGRST_DB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgrest-secret
                  key: db-uri
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
