apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-whoami
  labels:
    app: whoami
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
